import { Kanit, Noto_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body
        className={`${kanit.variable} ${notoSans.variable} antialiased`}
        style={{
          fontFamily: "var(--font-kanit), var(--font-noto-sans), sans-serif"
        }}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
